const medicineData = [
    {
        name: "Paracetamol 500mg",
        description: "Used for fever and pain relief. Common over-the-counter medicine.",
        price: 15.00,
        stock: 1000,
        category: "Pain Relief",
        manufacturer: "Cipla",
        expiryDate: new Date("2025-12-31"),
        prescriptionRequired: false,
        imageUrl: "https://plus.unsplash.com/premium_photo-1723921254681-1cd80686b44e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8UGFyYWNldGFtb2wlMjA1MDBtZ3xlbnwwfHwwfHx8MA%3D%3D",
        isActive: true
    },
    {
        name: "Amoxicillin 500mg",
        description: "Antibiotic used to treat bacterial infections.",
        price: 120.00,
        stock: 500,
        category: "Antibiotics",
        manufacturer: "Sun Pharma",
        expiryDate: new Date("2025-06-30"),
        prescriptionRequired: true,
        imageUrl: "https://media.istockphoto.com/id/2215337200/photo/liquid-amoxicillin-bottle-for-children.jpg?s=1024x1024&w=is&k=20&c=XC5kqo8Bc7yJSmph0Z6i1VyGmXUsEmsy3AIz6x5816E=",
        isActive: true
    },
    {
        name: "Cetirizine 10mg",
        description: "Antihistamine for allergy relief.",
        price: 25.00,
        stock: 800,
        category: "Allergy",
        manufacturer: "Glenmark",
        expiryDate: new Date("2025-08-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/cetirizin-sandoz-10-mg-dihydrochlorid-allergy-1067828777",
        isActive: true
    },
    {
        name: "Omeprazole 20mg",
        description: "Used to treat acid reflux and stomach ulcers.",
        price: 95.00,
        stock: 600,
        category: "Gastrointestinal",
        manufacturer: "Torrent",
        expiryDate: new Date("2025-07-31"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/playa-blanca-lanzarote-spain-april-25th-189519179",
        isActive: true
    },
    {
        name: "ORS (Oral Rehydration Solution)",
        description: "Used to treat dehydration, especially in cases of diarrhea.",
        price: 10.00,
        stock: 2000,
        category: "First Aid",
        manufacturer: "Electral",
        expiryDate: new Date("2025-12-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/electrolyte-ors-medicine-packed-sachets-different-1868337553",
        isActive: true
    },
    {
        name: "Iron + Folic Acid Tablets",
        description: "Supplements for treating and preventing anemia.",
        price: 45.00,
        stock: 1000,
        category: "Supplements",
        manufacturer: "Himalaya",
        expiryDate: new Date("2025-10-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/manchester-england-october-31st-2024-box-2540249353",
        isActive: true
    },
    {
        name: "Azithromycin 500mg",
        description: "Antibiotic for treating various bacterial infections.",
        price: 150.00,
        stock: 400,
        category: "Antibiotics",
        manufacturer: "Lupin",
        expiryDate: new Date("2025-05-31"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/cairo-egypt-october-15-2023-azithromycin-2375787829",
        isActive: true
    },
    {
        name: "Vitamin D3 1000IU",
        description: "Supplements for vitamin D deficiency.",
        price: 180.00,
        stock: 500,
        category: "Supplements",
        manufacturer: "HealthVit",
        expiryDate: new Date("2025-11-30"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/melbourne-vicaustraliasept-20th-2019-bottle-ostelin-1510014113",
        isActive: true
    },
    {
        name: "Amlodipine 5mg",
        description: "Used to treat high blood pressure and chest pain.",
        price: 65.00,
        stock: 700,
        category: "Cardiovascular",
        manufacturer: "Cadila",
        expiryDate: new Date("2025-08-31"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/vancouver-canada-august-8-2024-amlodipine-2502936831",
        isActive: true
    },
    {
        name: "Diclofenac Gel 1%",
        description: "Topical pain relief gel for joint and muscle pain.",
        price: 85.00,
        stock: 300,
        category: "Pain Relief",
        manufacturer: "Volini",
        expiryDate: new Date("2025-07-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/chonburi-thailandaugust-9-2018-voltaren-emulgel-1217997172",
        isActive: true
    },
    {
        name: "Metronidazole 400mg",
        description: "Antibiotic used to treat various infections.",
        price: 55.00,
        stock: 450,
        category: "Antibiotics",
        manufacturer: "Alkem",
        expiryDate: new Date("2025-09-30"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/metronidazole-medical-liquid-injection-glass-vial-2152504671",
        isActive: true
    },
    {
        name: "Aspirin 75mg",
        description: "Used for pain relief and to prevent heart attacks and strokes.",
        price: 20.00,
        stock: 800,
        category: "Pain Relief",
        manufacturer: "Bayer",
        expiryDate: new Date("2025-10-31"),
        prescriptionRequired: false,
        imageUrl:"https://www.shutterstock.com/image-photo/aspirin-pills-transparent-bottle-labeled-100-2560672303",
        isActive: true
    },
    {
        name: "Calcium + Vitamin D3",
        description: "Supplements for bone health and calcium deficiency.",
        price: 120.00,
        stock: 600,
        category: "Supplements",
        manufacturer: "Calcium Sandoz",
        expiryDate: new Date("2025-11-30"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/2403-lviv-ukraine-bottle-vitamin-d3-2607444831",
        isActive: true
    },
    {
        name: "Ciprofloxacin 500mg",
        description: "Antibiotic for treating various bacterial infections.",
        price: 95.00,
        stock: 450,
        category: "Antibiotics",
        manufacturer: "Cipla",
        expiryDate: new Date("2025-08-31"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/irvine-scotland-uk-june-17-2024-2492280287",
        isActive: true
    },
    {
        name: "Dexamethasone 0.5mg",
        description: "Corticosteroid used to treat various conditions including inflammation.",
        price: 35.00,
        stock: 700,
        category: "Steroids",
        manufacturer: "Zydus",
        expiryDate: new Date("2025-09-30"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/nurse-preparing-medical-treatment-dexamethasone-vial-1819520408",
        isActive: true
    },
    {
        name: "Folic Acid 5mg",
        description: "Vitamin supplement for pregnant women and anemia prevention.",
        price: 25.00,
        stock: 1000,
        category: "Supplements",
        manufacturer: "Himalaya",
        expiryDate: new Date("2025-12-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/cairo-egypt-december-2-2024-folic-2553235185",
        isActive: true
    },
    {
        name: "Hydrocortisone Cream 1%",
        description: "Topical steroid for skin conditions and allergies.",
        price: 45.00,
        stock: 400,
        category: "Skin Care",
        manufacturer: "Glenmark",
        expiryDate: new Date("2025-12-31"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/hydrocortisone-cream-medical-tube-closeup-2152504671",
        isActive: true
    },
    {
        name: "Ibuprofen 400mg",
        description: "Non-steroidal anti-inflammatory drug for pain and fever.",
        price: 30.00,
        stock: 900,
        category: "Pain Relief",
        manufacturer: "Cipla",
        expiryDate: new Date("2025-10-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/southminster-essex-06122020-box-84-ibuprofen-1754924603",
        isActive: true
    },
    {
        name: "Multivitamin Tablets",
        description: "Daily multivitamin supplement for overall health.",
        price: 150.00,
        stock: 500,
        category: "Supplements",
        manufacturer: "HealthVit",
        expiryDate: new Date("2025-11-30"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/multicolored-medical-pills-female-hands-side-2362447447",
        isActive: true
    },
    {
        name: "Ranitidine 150mg",
        description: "Used to treat and prevent stomach ulcers and acid reflux.",
        price: 40.00,
        stock: 750,
        category: "Gastrointestinal",
        manufacturer: "Sun Pharma",
        expiryDate: new Date("2025-08-31"),
        prescriptionRequired: false,
        imageUrl: "https://www.shutterstock.com/image-photo/ranitidine-histamine2-h2-receptor-antagonist-gerd-2298660191",
        isActive: true
    },
    {
        name: "Salbutamol Inhaler",
        description: "Bronchodilator for asthma and breathing problems.",
        price: 180.00,
        stock: 300,
        category: "Respiratory",
        manufacturer: "Cipla",
        expiryDate: new Date("2025-09-30"),
        prescriptionRequired: true,
        imageUrl: "https://www.shutterstock.com/image-photo/male-hand-pressing-his-bronchodilator-medicine-1821074570",
        isActive: true
    }
];

module.exports = medicineData; 